import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'home': 'Home',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'settings': 'Settings',
      'must_visit_spots': 'Must-Visit Spots',
      'going_to': 'Going to ...',
      'see_all': 'See All',
      'discover_nearby_locations': 'Discover nearby locations ? ',
      'search': 'Search',
      'view_map': 'View Map',
      'listen_to_audio_guide': 'Listen to Audio Guide',
      'error_navigating_to_search': 'Error navigating to search: ',
      'error_navigating_to_map': 'Error navigating to map: ',
      'error_navigating_to_nearby': 'Error navigating to nearby sites: ',
      'error_navigating_to_place_details': 'Error navigating to place details: ',
      'error_loading_places': 'Error loading places',
      'error_loading_recommended_places': 'Error loading recommended places',
      'failed_to_load_places': 'Failed to load places: ',
      'error_saving_place': 'Error saving place: ',
      'error_loading_saved_places': 'Error loading saved places: ',
      'please_enable_location': 'Please enable location services',
      'location_permission_denied': 'Location permission denied',
      'location_permission_permanent_denied': 'Location permission permanently denied',
      'error_getting_location': 'Error getting location: ',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone',
      'view_favorites': 'View Favorites',
      'edit_profile': 'Edit Profile',
      'edit_profile_mock': 'Edit Profile (mock feature)',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'audio_guide_language': 'Audio Guide Language',
      'notifications': 'Notifications',
      'go_premium': 'Go Premium',
      'premium_description': 'Unlock offline maps, ad-free experience, and exclusive content with a premium subscription.',
      'subscribe': 'Subscribe',
      'premium_redirect_mock': 'Redirect to premium subscription (mock).',
      'about_app': 'About App',
      'logout': 'Logout',
      'logout_confirmation': 'Logout Confirmation',
      'logout_question': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'toggle_view': 'Toggle View',
      'no_favorite_places_yet': 'No favorite places yet',
      'Search': 'Search',
      'Hidden_gems': 'Hidden Gems',
      'suggest_a_place': 'Suggest a Place',
      'suggest_hidden_gem': 'Suggest a Hidden Gem',
      'place_name': 'Place Name',
      'please_enter_name': 'Please enter a name',
      'description': 'Description',
      'please_enter_description': 'Please enter a description',
      'city': 'City',
      'Cairo': 'Cairo',
      'Alexandria': 'Alexandria',
      'South_Sinai': 'South Sinai',
      'Red_Sea': 'Red Sea',
      'Fayoum': 'Fayoum',
      'Search_for_a_place': 'Search for a Place',
      'suggested_trip': 'Suggested Trip',
      'refresh': 'Refresh',
      'your_trip': 'Your trip',
      'your_trips': 'Your trips',
      'create_trip': 'Create a trip',
      'no_trip_yet': 'No Trip Yet',
      'Account': 'Account',
      'search_for_a_place_ellipsis': 'Search for a place...',
      'no_places_found': 'No places found',
      'back': 'Back',
      'category': 'Category',
      'governorate': 'Governorate',
      'minimum_rating': 'Minimum Rating',
      'clear_filters': 'Clear Filters',
      'retry': 'Retry',
      'Nearby locations': 'Nearby locations',
      'recommended_for_you': 'Recommended for you',
      'nearby_hotels': 'Nearby Hotels',
      'no_hotels_found': 'No hotels found',
      'error_loading_nearby_hotels': 'Error loading nearby hotels',
      'auth_token_missing': 'Authentication token missing',
      'profile_updated': 'Profile updated successfully',
      'profile_update_failed': 'Profile update failed',
      'personal_information': 'Personal Information',
      'enter_name': 'Enter name',
      'name_required': 'Name is required',
      'enter_email': 'Enter email',
      'email_required': 'Email is required',
      'invalid_email': 'Invalid email address',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'enter_current_password': 'Enter current password',
      'current_password_required': 'Current password is required',
      'enter_new_password': 'Enter new password',
      'forgot_password': 'Forgot Password',
      'new_password': 'New Password',
      'save': 'Save',
      'failed_to_load_user_data': 'Failed to load user data',
      'password_updated': 'Password updated successfully',
      'wrong_current_password': 'Incorrect current password',
      'weak_password': 'The new password is too weak',
      'requires_recent_login': 'Please log in again to change password',
      'reset_email_sent': 'Password reset email sent. Check your inbox.',
      'reset_email_failed': 'Failed to send reset email',
      'send': 'Send',
      'enter_phone': 'Enter phone number',
      'phone_required': 'Phone number is required',
      'invalid_phone': 'Invalid phone number format',
    },
    'ar': {
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'must_visit_spots': 'أماكن يجب زيارتها',
      'going_to': 'ذاهب إلى ...',
      'see_all': 'عرض الكل',
      'discover_nearby_locations': 'تعرف على أماكن قريبة ؟',
      'search': 'بحث',
      'view_map': 'عرض الخريطة',
      'listen_to_audio_guide': 'استمع إلى الدليل الصوتي',
      'error_navigating_to_search': 'خطأ في الانتقال إلى البحث ',
      'error_navigating_to_map': 'خطأ في الانتقال إلى الخريطة ',
      'error_navigating_to_nearby': 'خطأ في الانتقال إلى المواقع القريبة ',
      'error_navigating_to_place_details':' خطأ في الانتقال إلى تفاصيل المكان ',
      'error_loading_places': 'خطأ في تحميل الأماكن',
      'error_loading_recommended_places': 'خطأ في تحميل الأماكن الموصى بها',
      'failed_to_load_places': 'فشل في تحميل الأماكن ',
      'error_saving_place': 'خطأ في حفظ المكان ',
      'error_loading_saved_places': 'خطأ في تحميل الأماكن المحفوظة ',
      'please_enable_location': 'يرجى تفعيل خدمات الموقع',
      'location_permission_denied': 'تم رفض إذن الموقع',
      'location_permission_permanent_denied': 'تم رفض إذن الموقع بشكل دائم',
      'error_getting_location': 'خطأ في الحصول على الموقع: ',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'view_favorites': 'عرض المفضلة',
      'edit_profile': 'تعديل الملف الشخصي',
      'edit_profile_mock': 'تعديل الملف الشخصي (ميزة محاكاة)',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'audio_guide_language': 'لغة الدليل الصوتي',
      'notifications': 'الإشعارات',
      'go_premium': 'الاشتراك المميز',
      'premium_description': 'افتح الخرائط بدون اتصال، تجربة خالية من الإعلانات، ومحتوى حصري باشتراك مميز.',
      'subscribe': 'اشترك',
      'premium_redirect_mock': 'إعادة توجيه إلى الاشتراك المميز (محاكاة).',
      'about_app': 'عن التطبيق',
      'logout': 'تسجيل الخروج',
      'logout_confirmation': 'تأكيد تسجيل الخروج',
      'logout_question': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'toggle_view': 'تبديل العرض',
      'no_favorite_places_yet': 'لا توجد أماكن مفضلة بعد',
      'Search': 'البحث',
      'Hidden_gems': 'كنوز مخفية',
      'suggest_a_place': 'اقترح مكانًا',
      'suggest_hidden_gem': 'اقترح كنزًا مخفيًا',
      'place_name': 'اسم المكان',
      'please_enter_name': 'يرجى إدخال اسم',
      'description': 'الوصف',
      'please_enter_description': 'يرجى إدخال وصف',
      'city': 'المدينة',
      'Cairo': 'القاهرة',
      'Alexandria': 'الإسكندرية',
      'South_Sinai': 'جنوب سيناء',
      'Red_Sea': 'البحر الأحمر',
      'Fayoum': 'الفيوم',
      'Search_for_a_place': 'ابحث عن مكان',
      'suggested_trip': 'رحلة مقترحة',
      'refresh': 'تحديث',
      'your_trip': 'رحلتك',
      'your_trips': 'رحلاتك',
      'create_trip': 'إنشاء رحلة',
      'no_trip_yet': 'لا توجد رحلة بعد',
      'Account': 'الحساب',
      'search_for_a_place_ellipsis': 'ابحث عن مكان...',
      'no_places_found': 'لم يتم العثور على أماكن',
      'back': 'رجوع',
      'category': 'الفئة',
      'governorate': 'المحافظة',
      'minimum_rating': 'الحد الأدنى للتقييم',
      'clear_filters': 'مسح الفلاتر',
      'retry': 'إعادة المحاولة',
      'Nearby locations': 'اماكن قريبه',
      'recommended_for_you': 'مُوصى به لك',
      'nearby_hotels': 'فنادق قريبة',
      'no_hotels_found': 'لم يتم العثور على فنادق',
      'error_loading_nearby_hotels': 'خطأ في تحميل الفنادق القريبة',
      'auth_token_missing': 'رمز المصادقة مفقود',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح',
      'profile_update_failed': 'فشل تحديث الملف الشخصي',
      'personal_information': 'المعلومات الشخصية',
      'enter_name': 'أدخل الاسم',
      'name_required': 'الاسم مطلوب',
      'enter_email': 'أدخل البريد الإلكتروني',
      'email_required': 'البريد الإلكتروني مطلوب',
      'invalid_email': 'بريد إلكتروني غير صالح',
      'change_password': 'تغيير كلمة المرور',
      'current_password': 'كلمة المرور الحالية',
      'enter_current_password': 'أدخل كلمة المرور الحالية',
      'current_password_required': 'كلمة المرور الحالية مطلوبة',
      'enter_new_password': 'أدخل كلمة مرور جديدة',
      'forgot_password': 'نسيت كلمة المرور',
      'new_password': 'كلمة مرور جديدة',
      'save': 'حفظ',
      'failed_to_load_user_data': 'فشل تحميل بيانات المستخدم',
      'password_updated': 'تم تحديث كلمة المرور بنجاح',
      'wrong_current_password': 'كلمة المرور الحالية غير صحيحة',
      'weak_password': 'كلمة المرور الجديدة ضعيفة جدًا',
      'requires_recent_login': 'يرجى تسجيل الدخول مرة أخرى لتغيير كلمة المرور',
      'reset_email_sent': 'تم إرسال بريد إعادة تعيين كلمة المرور. تحقق من بريدك الوارد.',
      'reset_email_failed': 'فشل إرسال بريد إعادة التعيين',
      'send': 'إرسال',
      'enter_phone': 'أدخل رقم الهاتف',
      'phone_required': 'رقم الهاتف مطلوب',
      'invalid_phone': 'تنسيق رقم الهاتف غير صالح',
    },
    'fr': {
      'home': 'Accueil',
      'favorites': 'Favoris',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'must_visit_spots': 'Lieux à visiter absolument',
      'going_to': 'Aller à ...',
      'see_all': 'Voir tout',
      'discover_nearby_locations': 'Découvrir les lieux à proximité ?',
      'search': 'Rechercher',
      'view_map': 'Voir la carte',
      'listen_to_audio_guide': 'Écouter le guide audio',
      'error_navigating_to_search': 'Erreur de navigation vers la recherche : ',
      'error_navigating_to_map': 'Erreur de navigation vers la carte : ',
      'error_navigating_to_nearby': 'Erreur de navigation vers les sites proches : ',
      'error_navigating_to_place_details': 'Erreur de navigation vers les détails du lieu : ',
      'error_loading_places': 'Erreur de chargement des lieux',
      'error_loading_recommended_places': 'Erreur de chargement des lieux recommandés',
      'failed_to_load_places': 'Échec du chargement des lieux : ',
      'error_saving_place': 'Erreur d\'enregistrement du lieu : ',
      'error_loading_saved_places': 'Erreur de chargement des lieux enregistrés : ',
      'please_enable_location': 'Veuillez activer les services de localisation',
      'location_permission_denied': 'Autorisation de localisation refusée',
      'location_permission_permanent_denied': 'Autorisation de localisation refusée définitivement',
      'error_getting_location': 'Erreur de récupération de la localisation : ',
      'name': 'Nom',
      'email': 'Email',
      'phone': 'Téléphone',
      'view_favorites': 'Voir les favoris',
      'edit_profile': 'Modifier le profil',
      'edit_profile_mock': 'Modifier le profil (fonctionnalité simulée)',
      'dark_mode': 'Mode sombre',
      'language': 'Langue',
      'audio_guide_language': 'Langue du guide audio',
      'notifications': 'Notifications',
      'go_premium': 'Passer en premium',
      'premium_description': 'Débloquez les cartes hors ligne, une expérience sans publicité et du contenu exclusif avec un abonnement premium.',
      'subscribe': 'S\'abonner',
      'premium_redirect_mock': 'Redirection vers l\'abonnement premium (simulée).',
      'about_app': 'À propos de l\'application',
      'logout': 'Déconnexion',
      'logout_confirmation': 'Confirmation de déconnexion',
      'logout_question': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'cancel': 'Annuler',
      'toggle_view': 'Basculer la vue',
      'no_favorite_places_yet': 'Aucun lieu favori pour l\'instant',
      'Search': 'Chercher',
      'Hidden_gems': 'Pépites cachées',
      'suggest_a_place': 'Suggérer un lieu',
      'suggest_hidden_gem': 'Suggérer une pépite cachée',
      'place_name': 'Nom du lieu',
      'please_enter_name': 'Veuillez entrer un nom',
      'description': 'Description',
      'please_enter_description': 'Veuillez entrer une description',
      'city': 'Ville',
      'Cairo': 'Le Caire',
      'Alexandria': 'Alexandrie',
      'South_Sinai': 'Sud Sinaï',
      'Red_Sea': 'Mer Rouge',
      'Fayoum': 'Fayoum',
      'Search_for_a_place': 'Rechercher un lieu',
      'suggested_trip': 'Voyage suggéré',
      'refresh': 'Actualiser',
      'your_trip': 'Votre voyage',
      'your_trips': 'Vos voyages',
      'create_trip': 'Créer un voyage',
      'no_trip_yet': 'Pas encore de voyage',
      'Account': 'Compte',
      'search_for_a_place_ellipsis': 'Rechercher un lieu...',
      'no_places_found': 'Aucun lieu trouvé',
      'back': 'Retour',
      'category': 'Catégorie',
      'governorate': 'Gouvernorat',
      'minimum_rating': 'Note minimale',
      'clear_filters': 'Effacer les filtres',
      'retry': 'Réessayer',
      'Nearby locations': 'Emplacements à proximité',
      'recommended_for_you': 'Recommandé pour vous',
      'nearby_hotels': 'Hôtels à proximité',
      'no_hotels_found': 'Aucun hôtel trouvé',
      'error_loading_nearby_hotels': 'Erreur de chargement des hôtels à proximité',
      'auth_token_missing': 'Jeton d\'authentification manquant',
      'profile_updated': 'Profil mis à jour avec succès',
      'profile_update_failed': 'Échec de la mise à jour du profil',
      'personal_information': 'Informations personnelles',
      'enter_name': 'Entrez votre nom',
      'name_required': 'Le nom est requis',
      'enter_email': 'Entrez votre email',
      'email_required': 'L\'email est requis',
      'invalid_email': 'Adresse email invalide',
      'change_password': 'Changer le mot de passe',
      'current_password': 'Mot de passe actuel',
      'enter_current_password': 'Entrez votre mot de passe actuel',
      'current_password_required': 'Le mot de passe actuel est requis',
      'enter_new_password': 'Entrez un nouveau mot de passe',
      'forgot_password': 'Mot de passe oublié',
      'new_password': 'Nouveau mot de passe',
      'save': 'Enregistrer',
      'failed_to_load_user_data': 'Échec du chargement des données utilisateur',
      'password_updated': 'Mot de passe mis à jour avec succès',
      'wrong_current_password': 'Mot de passe actuel incorrect',
      'weak_password': 'Le nouveau mot de passe est trop faible',
      'requires_recent_login': 'Veuillez vous reconnecter pour changer le mot de passe',
      'reset_email_sent': 'Email de réinitialisation envoyé. Vérifiez votre boîte de réception.',
      'reset_email_failed': 'Échec de l\'envoi de l\'email de réinitialisation',
      'send': 'Envoyer',
      'enter_phone': 'Entrez votre numéro de téléphone',
      'phone_required': 'Le numéro de téléphone est requis',
      'invalid_phone': 'Format de numéro de téléphone invalide',
    },
    'uk': {
      'home': 'Головна',
      'favorites': 'Улюблені',
      'profile': 'Профіль',
      'settings': 'Налаштування',
      'must_visit_spots': 'Обов\'язкові до відвідування місця',
      'going_to': 'Йду до ...',
      'see_all': 'Дивитися все',
      'discover_nearby_locations': 'Відкрийте для себе місця поблизу ? ',
      'search': 'Пошук',
      'view_map': 'Переглянути карту',
      'listen_to_audio_guide': 'Слухати аудіогід',
      'error_navigating_to_search': 'Помилка переходу до пошуку: ',
      'error_navigating_to_map': 'Помилка переходу до карти: ',
      'error_navigating_to_nearby': 'Помилка переходу до поближчих місць: ',
      'error_navigating_to_place_details': 'Помилка переходу до деталей місця: ',
      'error_loading_places': 'Помилка завантаження місць',
      'error_loading_recommended_places': 'Помилка завантаження рекомендованих місць',
      'failed_to_load_places': 'Не вдалося завантажити місця: ',
      'error_saving_place': 'Помилка збереження місця: ',
      'error_loading_saved_places': 'Помилка завантаження збережених місць: ',
      'please_enable_location': 'Будь ласка, увімкніть послуги геолокації',
      'location_permission_denied': 'Дозвіл на геолокацію відхилено',
      'location_permission_permanent_denied': 'Дозвіл на геолокацію постійно відхилено',
      'error_getting_location': 'Помилка отримання геолокації: ',
      'name': 'Ім\'я',
      'email': 'Електронна пошта',
      'phone': 'Телефон',
      'view_favorites': 'Переглянути улюблені',
      'edit_profile': 'Редагувати профіль',
      'edit_profile_mock': 'Редагувати профіль (імітація функції)',
      'dark_mode': 'Темний режим',
      'language': 'Мова',
      'audio_guide_language': 'Мова аудіогіда',
      'notifications': 'Сповіщення',
      'go_premium': 'Перейти на преміум',
      'premium_description': 'Розблоковуйте офлайн-карти, досвід без реклами та ексклюзивний контент за допомогою преміум-підписки.',
      'subscribe': 'Підписатися',
      'premium_redirect_mock': 'Перенаправлення на преміум-підписку (імітація).',
      'about_app': 'Про додаток',
      'logout': 'Вихід',
      'logout_confirmation': 'Підтвердження виходу',
      'logout_question': 'Ви впевнені, що хочете вийти?',
      'cancel': 'Скасувати',
      'toggle_view': 'Перемкнути вигляд',
      'no_favorite_places_yet': 'Ще немає улюблених місць',
      'Search': 'пошук',
      'Hidden_gems': 'Приховані перлини',
      'suggest_a_place': 'Запропонувати місце',
      'suggest_hidden_gem': 'Запропонувати приховану перлину',
      'place_name': 'Назва місця',
      'please_enter_name': 'Будь ласка, введіть назву',
      'description': 'Опис',
      'please_enter_description': 'Будь ласка, введіть опис',
      'city': 'Місто',
      'Cairo': 'Каїр',
      'Alexandria': 'Олександрія',
      'South_Sinai': 'Південний Синай',
      'Red_Sea': 'Червоне море',
      'Fayoum': 'Файюм',
      'Search_for_a_place': 'Пошук місця',
      'suggested_trip': 'Запропонована подорож',
      'refresh': 'Оновити',
      'your_trip': 'Ваша подорож',
      'your_trips': 'Ваші подорожі',
      'create_trip': 'Створити подорож',
      'no_trip_yet': 'Ще немає подорожей',
      'Account': 'Акаунт',
      'search_for_a_place_ellipsis': 'Пошук місця...',
      'no_places_found': 'Місць не знайдено',
      'back': 'Назад',
      'category': 'Категорія',
      'governorate': 'Губернаторство',
      'minimum_rating': 'Мінімальний рейтинг',
      'clear_filters': 'Очистити фільтри',
      'retry': 'Спробувати знову',
      'Nearby locations': 'поблизу місця',
      'recommended_for_you': 'Рекомендовано для вас',
      'nearby_hotels': 'Готелі поблизу',
      'no_hotels_found': 'Готелів не знайдено',
      'error_loading_nearby_hotels': 'Помилка завантаження готелів поблизу',
      'auth_token_missing': 'Відсутній токен аутентифікації',
      'profile_updated': 'Профіль успішно оновлено',
      'profile_update_failed': 'Не вдалося оновити профіль',
      'personal_information': 'Особиста інформація',
      'enter_name': 'Введіть ім\'я',
      'name_required': 'Ім\'я обов\'язкове',
      'enter_email': 'Введіть email',
      'email_required': 'Email обов\'язковий',
      'invalid_email': 'Невірна email адреса',
      'change_password': 'Змінити пароль',
      'current_password': 'Поточний пароль',
      'enter_current_password': 'Введіть поточний пароль',
      'current_password_required': 'Поточний пароль обов\'язковий',
      'enter_new_password': 'Введіть новий пароль',
      'forgot_password': 'Забули пароль',
      'new_password': 'Новий пароль',
      'save': 'Зберегти',
      'failed_to_load_user_data': 'Не вдалося завантажити дані користувача',
      'password_updated': 'Пароль успішно оновлено',
      'wrong_current_password': 'Невірний поточний пароль',
      'weak_password': 'Новий пароль занадто слабкий',
      'requires_recent_login': 'Будь ласка, увійдіть знову, щоб змінити пароль',
      'reset_email_sent': 'Лист для скидання пароля надіслано. Перевірте свою поштову скриньку.',
      'reset_email_failed': 'Не вдалося надіслати листа для скидання',
      'send': 'Надіслати',
      'enter_phone': 'Введіть номер телефону',
      'phone_required': 'Номер телефону обов\'язковий',
      'invalid_phone': 'Невірний формат номеру телефону',
    },
    'de': {
      'home': 'Startseite',
      'favorites': 'Favoriten',
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'must_visit_spots': 'Einen Besuch wert',
      'going_to': 'Gehe zu ...',
      'see_all': 'Alle ansehen',
      'discover_nearby_locations': 'Entdecken Sie nahegelegene Orte ?',
      'search': 'Suche',
      'view_map': 'Karte anzeigen',
      'listen_to_audio_guide': 'Audioführung anhören',
      'error_navigating_to_search': 'Fehler beim Navigieren zur Suche: ',
      'error_navigating_to_map': 'Fehler beim Navigieren zur Karte: ',
      'error_navigating_to_nearby': 'Fehler beim Navigieren zu nahegelegenen Orten: ',
      'error_navigating_to_place_details': 'Fehler beim Navigieren zu den Ortsdetails: ',
      'error_loading_places': 'Fehler beim Laden der Orte',
      'error_loading_recommended_places': 'Fehler beim Laden empfohlener Orte',
      'failed_to_load_places': 'Fehler beim Laden der Orte: ',
      'error_saving_place': 'Fehler beim Speichern des Ortes: ',
      'error_loading_saved_places': 'Fehler beim Laden gespeicherter Orte: ',
      'please_enable_location': 'Bitte aktivieren Sie die Standortdienste',
      'location_permission_denied': 'Standortberechtigung abgelehnt',
      'location_permission_permanent_denied': 'Standortberechtigung dauerhaft abgelehnt',
      'error_getting_location': 'Fehler beim Abrufen des Standorts: ',
      'name': 'Name',
      'email': 'E-Mail',
      'phone': 'Telefon',
      'view_favorites': 'Favoriten anzeigen',
      'edit_profile': 'Profil bearbeiten',
      'edit_profile_mock': 'Profil bearbeiten (Mock-Funktion)',
      'dark_mode': 'Dunkler Modus',
      'language': 'Sprache',
      'audio_guide_language': 'Sprache des Audioführers',
      'notifications': 'Benachrichtigungen',
      'go_premium': 'Premium erhalten',
      'premium_description': 'Entsperren Sie Offline-Karten, werbefreie Erfahrung und exklusiven Inhalt mit einem Premium-Abonnement.',
      'subscribe': 'Abonnieren',
      'premium_redirect_mock': 'Weiterleitung zu Premium-Abonnement (Mock).',
      'about_app': 'Über die App',
      'logout': 'Abmelden',
      'logout_confirmation': 'Abmeldung bestätigen',
      'logout_question': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
      'cancel': 'Abbrechen',
      'toggle_view': 'Ansicht umschalten',
      'no_favorite_places_yet': 'Noch keine Favoritenorte',
      'Search': 'Suche',
      'Hidden_gems': 'Versteckte Juwelen',
      'suggest_a_place': 'Ort vorschlagen',
      'suggest_hidden_gem': 'Verstecktes Juwel vorschlagen',
      'place_name': 'Ortsname',
      'please_enter_name': 'Bitte geben Sie einen Namen ein',
      'description': 'Beschreibung',
      'please_enter_description': 'Bitte geben Sie eine Beschreibung ein',
      'city': 'Stadt',
      'Cairo': 'Kairo',
      'Alexandria': 'Alexandria',
      'South_Sinai': 'Südsinai',
      'Red_Sea': 'Rotes Meer',
      'Fayoum': 'Fayoum',
      'Search_for_a_place': 'Ort suchen',
      'suggested_trip': 'Vorgeschlagene Reise',
      'refresh': 'Aktualisieren',
      'your_trip': 'Ihre Reise',
      'your_trips': 'Ihre Reisen',
      'create_trip': 'Reise erstellen',
      'no_trip_yet': 'Noch keine Reise',
      'Account': 'Konto',
      'search_for_a_place_ellipsis': 'Ort suchen...',
      'no_places_found': 'Keine Orte gefunden',
      'back': 'Zurück',
      'category': 'Kategorie',
      'governorate': 'Gouvernement',
      'minimum_rating': 'Mindestbewertung',
      'clear_filters': 'Filter löschen',
      'retry': 'Erneut versuchen',
      'Nearby locations': 'nahe gelegene Standorte',
      'recommended_for_you': 'Empfohlen für Sie',
      'nearby_hotels': 'Hotels in der Nähe',
      'no_hotels_found': 'Keine Hotels gefunden',
      'error_loading_nearby_hotels': 'Fehler beim Laden der Hotels in der Nähe',
      'auth_token_missing': 'Authentifizierungstoken fehlt',
      'profile_updated': 'Profil erfolgreich aktualisiert',
      'profile_update_failed': 'Profilaktualisierung fehlgeschlagen',
      'personal_information': 'Persönliche Informationen',
      'enter_name': 'Namen eingeben',
      'name_required': 'Name ist erforderlich',
      'enter_email': 'E-Mail eingeben',
      'email_required': 'E-Mail ist erforderlich',
      'invalid_email': 'Ungültige E-Mail-Adresse',
      'change_password': 'Passwort ändern',
      'current_password': 'Aktuelles Passwort',
      'enter_current_password': 'Aktuelles Passwort eingeben',
      'current_password_required': 'Aktuelles Passwort ist erforderlich',
      'enter_new_password': 'Neues Passwort eingeben',
      'forgot_password': 'Passwort vergessen',
      'new_password': 'Neues Passwort',
      'save': 'Speichern',
      'failed_to_load_user_data': 'Fehler beim Laden der Benutzerdaten',
      'password_updated': 'Passwort erfolgreich aktualisiert',
      'wrong_current_password': 'Aktuelles Passwort falsch',
      'weak_password': 'Das neue Passwort ist zu schwach',
      'requires_recent_login': 'Bitte melden Sie sich erneut an, um das Passwort zu ändern',
      'reset_email_sent': 'Passwort-Reset-E-Mail gesendet. Überprüfen Sie Ihren Posteingang.',
      'reset_email_failed': 'Fehler beim Senden der Reset-E-Mail',
      'send': 'Senden',
      'enter_phone': 'Telefonnummer eingeben',
      'phone_required': 'Telefonnummer ist erforderlich',
      'invalid_phone': 'Ungültiges Telefonnummernformat',
    },
    'ru': {
      'home': 'Главная',
      'favorites': 'Избранное',
      'profile': 'Профиль',
      'settings': 'Настройки',
      'must_visit_spots': 'Места, которые стоит посетить',
      'going_to': 'Еду в ...',
      'see_all': 'Смотреть все',
      'discover_nearby_locations': 'Откройте для себя близлежащие места ?',
      'search': 'Поиск',
      'view_map': 'Посмотреть карту',
      'listen_to_audio_guide': 'Прослушать аудиогид',
      'error_navigating_to_search': 'Ошибка навигации к поиску: ',
      'error_navigating_to_map': 'Ошибка навигации к карте: ',
      'error_navigating_to_nearby': 'Ошибка навигации к близлежащим местам: ',
      'error_navigating_to_place_details': 'Ошибка навигации к деталям места: ',
      'error_loading_places': 'Ошибка загрузки мест',
      'error_loading_recommended_places': 'Ошибка загрузки рекомендованных мест',
      'failed_to_load_places': 'Не удалось загрузить места: ',
      'error_saving_place': 'Ошибка сохранения места: ',
      'error_loading_saved_places': 'Ошибка загрузки сохраненных мест: ',
      'please_enable_location': 'Пожалуйста, включите службы геолокации',
      'location_permission_denied': 'Разрешение на геолокацию отклонено',
      'location_permission_permanent_denied': 'Разрешение на геолокацию постоянно отклонено',
      'error_getting_location': 'Ошибка получения геолокации: ',
      'name': 'Имя',
      'email': 'Электронная почта',
      'phone': 'Телефон',
      'view_favorites': 'Просмотреть избранное',
      'edit_profile': 'Редактировать профиль',
      'edit_profile_mock': 'Редактировать профиль (мок-функция)',
      'dark_mode': 'Темный режим',
      'language': 'Язык',
      'audio_guide_language': 'Язык аудиогида',
      'notifications': 'Уведомления',
      'go_premium': 'Перейти на премиум',
      'premium_description': 'Разблоковывайте оффлайн-карты, опыт без рекламы и эксклюзивный контент с помощью премиум-подписки.',
      'subscribe': 'Подписаться',
      'premium_redirect_mock': 'Перенаправление на премиум-подписку (мок).',
      'about_app': 'О приложении',
      'logout': 'Выход',
      'logout_confirmation': 'Подтверждение выхода',
      'logout_question': 'Вы уверены, что хотите выйти?',
      'cancel': 'Отмена',
      'toggle_view': 'Переключить вид',
      'no_favorite_places_yet': 'Пока нет любимых мест',
      'Search': 'поиск',
      'Hidden_gems': 'Скрытые жемчужины',
      'suggest_a_place': 'Предложить место',
      'suggest_hidden_gem': 'Предложить скрытую жемчужину',
      'place_name': 'Название места',
      'please_enter_name': 'Пожалуйста, введите название',
      'description': 'Описание',
      'please_enter_description': 'Пожалуйста, введите описание',
      'city': 'Город',
      'Cairo': 'Каир',
      'Alexandria': 'Александрия',
      'South_Sinai': 'Южный Синай',
      'Red_Sea': 'Красное море',
      'Fayoum': 'Файюм',
      'Search_for_a_place': 'Поиск места',
      'suggested_trip': 'Предложенная поездка',
      'refresh': 'Обновить',
      'your_trip': 'Ваша поездка',
      'your_trips': 'Ваши поездки',
      'create_trip': 'Создать поездку',
      'no_trip_yet': 'Пока нет поездок',
      'Account': 'Аккаунт',
      'search_for_a_place_ellipsis': 'Поиск места...',
      'no_places_found': 'Места не найдены',
      'back': 'Назад',
      'category': 'Категория',
      'governorate': 'Губернаторство',
      'minimum_rating': 'Минимальный рейтинг',
      'clear_filters': 'Очистить фильтры',
      'retry': 'Повторить',
      'Nearby locations': 'близлежащие локации',
      'recommended_for_you': 'Рекомендуем вам',
      'nearby_hotels': 'Отели поблизости',
      'no_hotels_found': 'Отели не найдены',
      'error_loading_nearby_hotels': 'Ошибка загрузки отелей поблизости',
      'auth_token_missing': 'Отсутствует токен аутентификации',
      'profile_updated': 'Профиль успешно обновлен',
      'profile_update_failed': 'Не удалось обновить профиль',
      'personal_information': 'Персональная информация',
      'enter_name': 'Введите имя',
      'name_required': 'Имя обязательно',
      'enter_email': 'Введите email',
      'email_required': 'Email обязателен',
      'invalid_email': 'Неверный email',
      'change_password': 'Изменить пароль',
      'current_password': 'Текущий пароль',
      'enter_current_password': 'Введите текущий пароль',
      'current_password_required': 'Текущий пароль обязателен',
      'enter_new_password': 'Введите новый пароль',
      'forgot_password': 'Забыли пароль',
      'new_password': 'Новый пароль',
      'save': 'Сохранить',
      'failed_to_load_user_data': 'Не удалось загрузить данные пользователя',
      'password_updated': 'Пароль успешно обновлен',
      'wrong_current_password': 'Неверный текущий пароль',
      'weak_password': 'Новый пароль слишком слабый',
      'requires_recent_login': 'Пожалуйста, войдите снова, чтобы изменить пароль',
      'reset_email_sent': 'Письмо для сброса пароля отправлено. Проверьте свою почту.',
      'reset_email_failed': 'Не удалось отправить письмо для сброса',
      'send': 'Отправить',
      'enter_phone': 'Введите номер телефона',
      'phone_required': 'Номер телефона обязателен',
      'invalid_phone': 'Неверный формат номера телефона',
    },
  };

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final instance = Localizations.of<AppLocalizations>(context, AppLocalizations);
    return instance ?? AppLocalizations('en');
  }

  final String _locale;

  AppLocalizations(this._locale);

  String translate(String key) {
    final localizedValue = _localizedValues[_locale]?[key] ?? _localizedValues['en']?[key];
    return localizedValue ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar', 'fr', 'uk', 'de', 'ru'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale.languageCode);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}